remove_existing: True 
sequential_data : False
pickle_path : "C:\\Projects\\seq2bbox\\data\\pickle\\ENA\\Test.pk"
dataset_path : "C:\\temp\\ENA_full\\"
image_path : "C:\\temp\\data_final\\ENA\\images\\ENA640xCropGNTest\\"
histlbp_path : "C:\\temp\\data_final\\ENA\\histlbp\\ENA640xCropGNTest\\"
label_path : "C:\\temp\\data_final\\ENA\\labels\\ENA640xCropGNTest\\"
generate_histlp : False 
generate_labels : True
convert_grayscale : True 
wavelet_compress : False
naive_compress : True 
resize : True 
image_size : 640 
# multiprocessing
chunksize : 8
max_workers : 8
