remove_existing: True 
sequential_data : False
pickle_path : "C:\\Projects\\seq2bbox\\data\\pickle\\ENA\\val.pk"
dataset_path : "C:\\temp\\ENA_full\\"
image_path : "C:\\temp\\data_final\\ENA\\images\\ENAORIGxCropRGBVal\\"
histlbp_path : "C:\\temp\\data_final\\ENA\\histlbp\\ENAORIGxCropRGBVal\\"
label_path : "C:\\temp\\data_final\\ENA\\labels\\ENAORIGxCropRGBVal\\"
generate_histlp : False 
generate_labels : True
convert_grayscale : False
wavelet_compress : False
naive_compress : False
resize : False 
image_size : 640 
# multiprocessing
chunksize : 8
max_workers : 8