c:/Projects/pyvenvs/wildsenv/Scripts/python.exe c:/Projects/seq2bbox/datapipeline.py -c ENA224xCropGWNTest.yaml
c:/Projects/pyvenvs/wildsenv/Scripts/python.exe c:/Projects/seq2bbox/datapipeline.py -c ENA224xCropGWNVal.yaml
c:/Projects/pyvenvs/wildsenv/Scripts/python.exe c:/Projects/seq2bbox/datapipeline.py -c ENA640xCropGNTest.yaml
c:/Projects/pyvenvs/wildsenv/Scripts/python.exe c:/Projects/seq2bbox/datapipeline.py -c ENA640xCropGNVal.yaml
c:/Projects/pyvenvs/wildsenv/Scripts/python.exe c:/Projects/seq2bbox/datapipeline.py -c ENA640xCropGTest.yaml
c:/Projects/pyvenvs/wildsenv/Scripts/python.exe c:/Projects/seq2bbox/datapipeline.py -c ENA640xCropGVal.yaml
c:/Projects/pyvenvs/wildsenv/Scripts/python.exe c:/Projects/seq2bbox/datapipeline.py -c ENA640xCropGWNTest.yaml
c:/Projects/pyvenvs/wildsenv/Scripts/python.exe c:/Projects/seq2bbox/datapipeline.py -c ENA640xCropGWNVal.yaml
c:/Projects/pyvenvs/wildsenv/Scripts/python.exe c:/Projects/seq2bbox/datapipeline.py -c ENA640xCropGWTest.yaml
c:/Projects/pyvenvs/wildsenv/Scripts/python.exe c:/Projects/seq2bbox/datapipeline.py -c ENA640xCropGWVal.yaml